### ISSUE TITLE
Grml's prompt raise error in bare git repos

### ISSUE THREAD

**Issue by cireu** [grml/grml-etc-core#103]
Version: 0.17.0
zsh: 5.8
Reproduce step:
```
git clone --bare --depth=1 https://github.com/grml/grml-etc-core
cd grml-etc-core.git
```
get following error after refresh prompt
```
fatal: this operation must be run in a work tree
```

**Comment by mika** [comment]
Ah interesting, I can reproduce this behavior on current Debian/testing with git version 2.26.2, though on Debian/buster with git version 2.20.1 (at least with my configuration) I don't see this behavior.

@ft any chance you could look into this?

**Comment by cireu** [comment]
> Ah interesting, I can reproduce this behavior on current Debian/testing with git version 2.26.2, though on Debian/buster with git version 2.20.1 (at least with my configuration) I don't see this behavior.
> 
> @ft any chance you could look into this?

Yes, I'm using 2.26.2.

**Comment by ft** [comment]
The bug is with zsh upstream, of course, where vcs-info lives.

The call that causes this is:

    gitbase=$( ${vcs_comm[cmd]} rev-parse --show-toplevel 2> /dev/null )
    fatal: this operation must be run in a work tree

Sooo... did git stop writing its error messages to stderr? This is odd.

**Comment by ft** [comment]
This would be a fix.

```diff
diff --git a/Functions/VCS_Info/Backends/VCS_INFO_get_data_git b/Functions/VCS_Info/Backends/VCS_INFO_get_data_git
index 79429c8e0..932a13423 100644
--- a/Functions/VCS_Info/Backends/VCS_INFO_get_data_git
+++ b/Functions/VCS_Info/Backends/VCS_INFO_get_data_git
@@ -138,10 +138,10 @@ VCS_INFO_git_handle_patches () {

 gitdir=${vcs_comm[gitdir]}
 VCS_INFO_git_getbranch ${gitdir}
-gitbase=$( ${vcs_comm[cmd]} rev-parse --show-toplevel 2> /dev/null )
-if [[ -z ${gitbase} ]]; then
-    # Bare repository
+if [[ "$(${vcs_comm[cmd]} rev-parse --is-bare-repository 2> /dev/null)" == 'true' ]]; then
     gitbase=${gitdir:P}
+else
+    gitbase=$( ${vcs_comm[cmd]} rev-parse --show-toplevel 2> /dev/null )
 fi
 rrn=${gitbase:t}
 if zstyle -t ":vcs_info:${vcs}:${usercontext}:${rrn}" get-revision ; then
```

I'll talk to upstream. (Which I used to be, but someone basically took over vcs-info maintenance, because I went way inactive…)

**Comment by ft** [comment]
Git still  writes the error to stderr. I wonder why the redirection doesn't put it into `/dev/null`.

Rabbit holes. Always deeper than you think. Meh.

**Comment by ft** [comment]
Here's the root of the thread upstream: http://zsh.org/mla/workers/2020/msg01056.html

**Comment by ft** [comment]
So. Long story short, I didn't check the current zsh repository and just assumed it went unfixed. But it's not.

It's actually this commit: bacad965

```
vcs_info git: avoid warnings in bare repositories

Git 2.25 introduced a change to how git rev-parse --show-toplevel
behaves.  Traditionally, it succeeded with no output if the user was
in a bare repository.  Now it dies, printing an error to standard error.
Consequently, when the user is in a bare repository with a newer Git,
vcs_info prints noisily to standard error.

While this is functionally harmless, it is annoying for the shell to
print messages from Git every time the prompt is printed, so let's
silence the error message.
```

Since this is fixed upstream and only happens in bare repositories,
I am against working around it.

mika: Feel free to reopen if you disagree strongly.

**Comment by mika** [comment]
@ft thanks for digging into this, I'm perfectly fine with your suggestion, thanks!
