### ISSUE TITLE
RFC for zshrc: disable smiley on failures in right side of shell prompt by default

### ISSUE THREAD

**Issue by mika** [grml/grml-etc-core#107]
I'm proposing to disable our smiley which appears if exit code != 0 on the right side of the prompt, like:

```
mika@lunge /tmp/tmp.kvMVtGqka4 % false
1 mika@lunge /tmp/tmp.kvMVtGqka4 %                                                          :(
```

IMO it's totally annoying for c/p.
I'm aware that users can control this behavior via:

```
# disable smiley
zstyle ':prompt:grml:right:setup' use-rprompt false
```

... in their personal zsh configuration, but I'd prefer to disable this by default, so folks don't have to manually remove it in c/p for docs etc.

If someone objects, please speak up! :)

**Comment by mika** [comment]
Ping @formorer @ft @jkirk @btittelbach @zeha for comments/opinions :)

**Comment by zeha** [comment]
Please do it, I've always turned this off in my config copies.
