### ISSUE TITLE
With /etc/zsh/zshrc unable to change the prompt through PROMPT/PS1 in ~/.zshrc

### ISSUE THREAD

**Issue by linuunix** [grml/grml-etc-core#111]
After some years I got a bit bored with the prompt and wanted to try a "new" one, so  I have:    
```
autoload -Uz promptinit && promptinit
unset PS1 PROMPT
PS1='%B%(!.%F{red}%n%f.%F{green}%n%f)%F{white}@%f%F{green}%m%f %40<..<%~%<< %(!.%F{red}# %f.%F{green}$ %f)%b'
PROMPT="$PS1"
```
in `~/.zshrc`
But the prompt doesn't change! Only if I `mv/rm /etc/zsh/zshrc`, then my changes are applied.   
AFAIK ~/.zshrc is sourced **after** /etc/zsh/zshrc, so am wondering why the system file is overriding my local user settings.
Or should I change it through the `zstyle ':prompt:grml:...' `, given I have no clue how to do it that way.    
I tried exporting only PS1, then PROMPT, then both. Still no change :(    

zsh v5.8
grml-zsh-config v0.17.4

**Comment by ft** [comment]
This is not a bug. It's actually documented in the PROMPT section of the setup's manual page¹.

Note that exporting variables will not help here at all. All that export does is put a variable in the shells execution environment.

Grml's zsh prompt is extremely extensible and custumisable. But if you prefer to take control yourself, you can either write your own theme (you're loading promptinit after all), or disable the prompt system and use PS1/PROMPT manually. This this from our manual to use a completely custom prompt:

    # Turn the prompt system off:
    prompt off
    # Customise the prompt yourself:
    PS1='%~ %# '

¹ https://grml.org/zsh/grmlzshrc.html
