### ISSUE TITLE
Preferred method for adding new or modifying default items?

### ISSUE THREAD

**Issue by barmadrid** [grml/grml-etc-core#112]
I need to modify few default tokens (items) and add new, for example:

`'%n '` (extra-space) instead of `'%n'` for user.

Each of the 2 commands below is giving me the same the desired effect (added to `~/.zshrc.local`):

**Modify item:**

`zstyle ':prompt:grml:*:items:user' token '%n '`
or
`grml_prompt_token_default[user]='%n '`

**Add new:**

`zstyle ':prompt:grml:*:items:window' token 'window '`
or
`grml_theme_add_token window 'window '`

Which option from above [grml_* or zstyle) is preferred (assuming, each give the same result)?

**Comment by mika** [comment]
@ft any chance you could take a look at this and give your feedback? :)

**Comment by ft** [comment]
You shouldn't change variables. They are more or less internal, as much as a shell allows for that.

The `grml_theme_add_token` function should be used to add tokens. Hence its name. See its usage output as well, if you call it without arguments. It takes care of setting everything that's required for these things to work.

To change the text of a token, modify the `token` style. For adding stuff before and after, use the `pre` and `post` styles.

I wrote a little about these things when we redid the whole prompt business:

- http://bewatermyfriend.org/p/2013/001/
- http://bewatermyfriend.org/p/2013/003/

The manual has some information too, as does the prompt-system's help output to the `grml` prompt.

**Comment by barmadrid** [comment]
@ft Thanks for the reply.

So we can use: `zstyle ':prompt:grml:*:items:user' token '%n '` to add space beside user name.

In regard to adding new item...in the articles above, you mention `grml_theme_add_token day '%D{%A}' '%F{green}' '%f'`

But if we want to keep the changes permanently (kept after close and reopen terminal) should we add: `grml_theme_add_token day '%D{%A}' '%F{green}' '%f'`
 **or** 
`zstyle ':prompt:grml:*:items:day' token '%D{%A}'` to `~/.zshrc.local `?

Because apparently, both work!

**Comment by ft** [comment]
Using the function to add tokens is the only supported way and it will remain the only supported way.

I am not guaranteeing that other ways work or even if they do now or appear to work now, that they will continue to do so. The function will do the right thing even if things change in the future.

**Comment by barmadrid** [comment]
Thanks for confirming.

Closing this as a result.
