### ISSUE TITLE
grml-zshrc: do not use histignorealldups by default

### ISSUE THREAD

**Issue by mika** [grml/grml-etc-core#114]
In our `grml-zshrc` we have:

```
# If a new command line being added to the history list duplicates an older
# one, the older command is removed from the list
is4 && setopt histignorealldups
```

This causes the following behavior in zsh history:

```
root@grml ~ # echo foo
foo
root@grml ~ # echo bar
bar
root@grml ~ # history -E 0
    1  14.10.2020 15:48  exec zsh
    2  14.10.2020 15:48  echo foo
    3  14.10.2020 15:48  echo bar
root@grml ~ # echo foo
foo
root@grml ~ # history -E 0
    1  14.10.2020 15:48  exec zsh
    3  14.10.2020 15:48  echo bar
    5  14.10.2020 15:48  echo foo
```

So the 2nd issue from the zsh history got removed, this is expected with `histignorealldups` being set.

But this means it's hard to reconstruct the order of commands that have been executed.

If we'd unset `histignorealldups` by default, the behavior would be instead:

```
root@grml ~ # setopt nohistignorealldups
root@grml ~ # echo foo
foo
root@grml ~ # echo bar
bar
root@grml ~ # echo foo
foo
root@grml ~ # history -E 0
    1  14.10.2020 15:49  exec zsh
    2  14.10.2020 15:50  setopt nohistignorealldups
    3  14.10.2020 15:50  echo foo
    4  14.10.2020 15:50  echo bar
    5  14.10.2020 15:50  echo foo
```

This indeed isn't so nice when browsing through history (e.g. via `<cursor-up>` since then you have all the duplicates), but instead it gives a better/full picture of what has been executed, which is especially useful for sysadmins IMO. I'm therefore suggesting to use `setopt nohistignorealldups` by default in grml-zshrc.

Opinions? /cc @grml/team-grml-developers 

FTR, I'm not really sure what this completion setting is for:

```
    # ignore duplicate entries
    zstyle ':completion:*:history-words'   remove-all-dups yes
    zstyle ':completion:*:history-words'   stop yes
```

@ft maybe you could enlighten me here? Maybe you also have any further ideas how to improve our grml-zshrc to get (closer to) the behavior I'm proposing? :)

**Comment by evgeni** [comment]
I *personally* like the current behavior, as I need a good search but don't care about the "full picture".

But then again I am using this on a normal laptop, not in an environment where I possible need to reconstruct what I did (like when trying to fix a broken system), so I can see the benefit for the project as a whole (and I can very well add a line to my zshrc.local).

**Comment by ft** [comment]
Yeah, I'm with Evgeni. I like the behaviour *personally*. But as you may know, I have my private setup, so I am cool either way you decide.

The styles are about the `_history_complete_word` widget. From the manual:

```
       stop   If set to `true', the  _history_complete_word  bindable  command
              will  stop  once  when reaching the beginning or end of the his‐
              tory.  Invoking _history_complete_word will then wrap around  to
              the  opposite  end  of  the  history.   If  this style is set to
              `false' (the default), _history_complete_word will loop  immedi‐
              ately as in a menu completion.
```

and

```
       remove-all-dups
              The _history_complete_word bindable  command  and  the  _history
              completer  use this to decide if all duplicate matches should be
              removed, rather than just consecutive duplicates.
```

They are unrelated to actual history behaviour.

**Comment by mika** [comment]
@ft thanks for pointing me to the appropriate place in the docs! (I'm afraid I still don't fully understand their behaviour but if that's unrelated to the actual history behaviour it's all good ;))

**Comment by jkirk** [comment]
I again stumbled over this one and as we all have a private setup, I'd vote to disable histignorealldups by default. It's a simple fix to enable histignorealldups but not as simple to recover the "big picture" once the duplicates are removed.

**Comment by ft** [comment]
Darshaka Pathirana wrote:
> I again stumbled over this one and as we all have a private setup, I'd vote to
> disable histignorealldups by default. It's a simple fix to enable
> histignorealldups but not as simple to recover the "big picture" once the
> duplicates are removed.

I personally prefer the histignorealldups behaviour. But that being
said, this is not a mountain I would die on. If Mika and others prefer
the default history behaviour, then we'll use that.

People can adjust this to their taste. The behaviour that we want on the
system, by default, ie Mika's preference, that's what the setup should
use.

**Comment by mika** [comment]
Thanks everyone for your feedback, so let's go with dropping the `histignorealldups` from our grml-zshrc, and provide a configuration snippet in `/etc/skel/.zshrc` instead.
