### ISSUE TITLE
grml-zshrc: Ignore setting up _etc_hosts if the file is too large

### ISSUE THREAD

**Issue by Atrate** [grml/grml-etc-core#118]
In situations where the hosts file is used for ad/malware blocking (e.g. utilizing [Steven Black's hosts file](https://github.com/StevenBlack/hosts)), grml-zshrc's generation of `_etc_hosts` can severely impact performance, especially on underpowered systems with low-end CPUs and HDDs, leading to very long loading times for the shell.

It would be nice if grml-zshrc ignored setting up `_etc_hosts` if it was too big (>1MiB maybe?) or allowed for it to be disabled through `.zshrc.pre`.

Once a decision is reached, I can make a simple PR with that

**Comment by mika** [comment]
Ah, interesting one. :) Hm, would `grep -v 0.0.0.0 /etc/hosts` help in any way to speed this up? Or is that still a problem then, performance wise? (I'm not at all objecting against improving the situation for your use case, just trying to understand what might be the best option for everyone :))

**Comment by Atrate** [comment]
> Ah, interesting one. :) Hm, would `grep -v 0.0.0.0 /etc/hosts` help in any way to speed this up? Or is that still a problem then, performance wise? (I'm not at all objecting against improving the situation for your use case, just trying to understand what might be the best option for everyone :))

Yeah, I haven't thought of approaching it that way. As far as I can tell, it improves the performance significantly.

There is one problem — there do exist hosts files that also use `::1` or `127.0.0.1` instead of `0.0.0.0` and including loopback in `-v` may cause `localhost` as a hostname not to get picked up.

For starters though, adding `-v 0.0.0.0` is certain to help significantly with most major hosts files.
