### ISSUE TITLE
What happened to version 18?

### ISSUE THREAD

**Issue by meator** [grml/grml-etc-core#120]
Hello, I am packaging grml-zsh-config for Voidlinux and I have noticed that https://deb.grml.org/pool/main/g/grml-etc-core/grml-etc-core_0.18.0.tar.gz has vanished. This is not the first time this has happened. The [0.17.4 version](https://deb.grml.org/pool/main/g/grml-etc-core/grml-etc-core_0.17.4.tar.gz) has also disappeared from the pool. Why is this happening? Package build fails with `Not found` because of this.

**Comment by mika** [comment]
@meator thanks for reaching out. Sorry, I wasn't aware of this, but as part of our Debian repository cleanups, versions that aren't part of any actual Grml release usually get automatically removed.

But we do have release tarballs available at https://github.com/grml/grml-etc-core/releases, those don't disappear and should serve as stable base. Do those work out for you?

**Comment by meator** [comment]
Thanks for the fast feedback! I'll switch it to GitHub releases. And Archlinux uses the same source.

**Comment by mika** [comment]
@meator great to hear! Please let me me know if something shouldn't work for you as needed, and please always feel free to reach out to us!
