### ISSUE TITLE
zshrc: unconditionally overwrites $COLORTERM

### ISSUE THREAD

**Issue by debfx** [grml/grml-etc-core#131]
zshrc unconditionally exports COLORTERM=yes. I can see the use case for setting it if the variable is missing.

However many terminal emulators set COLORTERM=truecolor. zshrc shouldn't overwrite this.

**Comment by mika** [comment]
Thanks for reporting, does https://github.com/grml/grml-etc-core/pull/132 solve your issue?

**Comment by debfx** [comment]
Yes, that works fine for me. Thanks!

**Comment by mika** [comment]
@debfx thanks, fixed! :)
