### ISSUE TITLE
zsh: Narrow xterm window causes troff errors

### ISSUE THREAD

**Issue by moviuro** [grml/grml-etc-core#148]
Hi,

Starting a xterm window that is relatively narrow causes errors to be printed on screen before the prompt.

```
troff: <standard input>:37: warning [p 1, 8.3i]: cannot adjust line
troff: <standard input>:65: warning [p 2, 4.7i]: cannot adjust line
troff: <standard input>:69: warning [p 2, 5.7i]: cannot adjust line
troff: <standard input>:69: warning [p 2, 5.8i]: cannot adjust line
troff: <standard input>:69: warning [p 2, 6.0i]: cannot adjust line
troff: <standard input>:166: warning [p 5, 1.5i]: cannot adjust line
troff: <standard input>:166: warning [p 5, 1.7i]: can't break line
troff: <standard input>:171: warning [p 5, 3.5i]: cannot adjust line
troff: <standard input>:176: warning [p 5, 5.3i]: can't break line
```

I have not found one reference to `troff` in `/etc/zsh/*` so I'm not sure where to look.

![troff error on narrow windows](https://user-images.githubusercontent.com/6882978/192248781-41c4ccfe-050b-4690-8c8e-25f5301c08f0.png)

**Comment by mika** [comment]
As a starting point, what Zsh version are you using?
Does it also happen if you switch to another prompt (other than `grml` or `grml-large`)?

**Comment by moviuro** [comment]
zsh 5.9 on archlinux

Oh, and yep, interestingly this behavior still happens with no grml setup at all on the machine. Weird!
