### ISSUE TITLE
File with BOM and not UTF-8 ?

### ISSUE THREAD

**Issue by flobee** [grml/grml-etc-core#155]
See my hints: 
https://github.com/flobee/grml-etc-core/commit/a9e10c865de2da935636dfe7456b8d5eaef45921

downloaded zshrc files from https://grml.org/zsh/ this way:
```
# IMPORTANT: please note that you might override an existing
# configuration file in the current working directory! =>
wget -O .zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc

# Optionally also grab the user configration:
# wget -O .zshrc.local  https://git.grml.org/f/grml-etc-core/etc/skel/.zshrc
```

Edit in kate and kate says: BOM exists and  Line 335 (#getanchors) look damaged.
But the browser tell also weired chars.: https://github.dev/grml/grml-etc-core/blob/master/etc/skel/.zshrc#L335C40-L335C47

**Comment by mika** [comment]
Ah nice catch, thanks @flobee! What about https://github.com/grml/grml-etc-core/pull/156?

**Comment by flobee** [comment]
I like #156 ;-) 


just saw your sys-admin presentation at media.ccc from '23. you'are talking very fast ... watched at 75% of speed :-D

**Comment by mika** [comment]
@flobee excellent, merged now! :)

Haha 8-)
