### ISSUE TITLE
History not saved since 0.19.9 when SAVEHIST is unset

### ISSUE THREAD

**Issue by Derppening** [grml/grml-etc-core#169]
After upgrading to 0.19.9, I realize that none of my history is saved anymore. 

I tried to debug this issue using `zsh -x` and noticed this line:

```
+/etc/zsh/zshrc:1684> HISTSIZE=30 
+/etc/zsh/zshrc:1685> SAVEHIST=0
```

I think with the change made in #166 didn't take into account that Zsh sets these variables by default, as shown below:

```
% zsh -d -f -i
% echo $HISTSIZE
30
% echo $SAVEHIST
0
```

Thus the `:-5000` and `:-10000` defaults that were present in the change is never applied.

I understand that I can manually set `HISTSIZE` and `SAVEHIST` in `$HOME/.zshrc`, but this behavior may be surprising to some users as the defaults are changed with no indication (e.g. a minor version bump).

**Comment by mika** [comment]
@Derppening uh nice catch, thanks for reporting this! We'll definitely need to address this, will take care ASAP

**Comment by unknowndevQwQ** [comment]
> I've uploaded grml-etc-core v0.19.10 which reverts the changes from #160 for now. Not sure whether we have a good way how to handle this, given that Zsh upstream sets `HISTSIZE=30` and `SAVEHIST=0` by default. :-/
> 
> @ft any idea what we could do about this?

```
[[ -z "${HISTSIZE}" ]] || (("${HISTSIZE}" >  30))
[[ -z "${SAVESIZE}" ]] || (("${SAVESIZE}" >  0))
```
I think...

**Comment by zeha** [comment]
```sh
if [ "${HISTSIZE}" = "30" ]; then
  # override settings only if defaults from zsh are in place
  HISTSIZE=5000
  SAVEHIST=10000 # useful for setopt append_history
fi
```

?

**Comment by mika** [comment]
Yeah, checking for HISTSIZE might be worth an idea! I'm only afraid that this might break as soon as zsh upstream changes this:

```
config.h.in:#define DEFAULT_HISTSIZE 30
configure.ac:#define DEFAULT_HISTSIZE 30
```

:thinking:

**Comment by zeha** [comment]
> Yeah, checking for HISTSIZE might be worth an idea! I'm only afraid that this might break as soon as zsh upstream changes this...

Well they haven't changed it since 1999 at least (git commit "Initial revision"). If they ever change it, grml zshrc users will need an update.

**Comment by unknowndevQwQ** [comment]
> > Yeah, checking for HISTSIZE might be worth an idea! I'm only afraid that this might break as soon as zsh upstream changes this...
> 
> Well they haven't changed it since 1999 at least (git commit "Initial revision"). If they ever change it, grml zshrc users will need an update.

Let try
```
[ "${HISTSIZE}" = "$( env -i zsh -dfc 'echo $HISTSIZE')" ] && {
...
}
```
this?

**Comment by zeha** [comment]
> ```
> [ "${HISTSIZE}" = "$(env -i zsh -dfc 'echo $HISTSIZE')" ] && {
> ...
> }
> ```

That seems extremely costly.

**Comment by unknowndevQwQ** [comment]
sigh

**Comment by mika** [comment]
> > Yeah, checking for HISTSIZE might be worth an idea! I'm only afraid that this might break as soon as zsh upstream changes this...
> 
> Well they haven't changed it since 1999 at least (git commit "Initial revision"). If they ever change it, grml zshrc users will need an update.

Good point, let's follow this approach then!
