### ISSUE TITLE
zsh-config: zshrc hangs if OLDPWD is no longer available

### ISSUE THREAD

**Issue by morxa** [grml/grml-etc-core#51]
I have a systemd automount, which is an external USB drive and thus not always available. If I have switched to the mount point recently and it is listed in `.zdirs`, but currently the drive is not available, zsh hangs while loading `/etc/zsh/zshrc`.

I assume this should also work with any other directories which are not available anymore.

### How to reproduce
1. Create an automount for `/mnt/usb`
2. `cd /mnt/usb`
3. Close the terminal
4. Umount `/mnt/usb` and unplug the device
5. Start a new terminal and load the profile from `/etc/zsh/zshrc`

### Expected behavior
The script should detect that `/mnt/usb` is no longer available and skip calling `cd /mnt/usb`.

### Actual behavior
In [line 1625](https://github.com/grml/grml-etc-core/blob/master/etc/zsh/zshrc#L1625) of the profile file, `cd /mnt/usb` is called. The call hangs because the device is longer available. Even after the automount times out, the terminal still doesn't finish loading the profile.

**Comment by ft** [comment]
The problem isn't OLDPWD but $dirstack[1] AFAICT.

I have just pushed ef0f2491f306bf6ca59 — which should deal with the problem.

Thanks for reporting and let us know if this fixes your issue!

**Comment by morxa** [comment]
Thanks, that fixed it!
