### ISSUE TITLE
New warning message appears when using the prompt command

### ISSUE THREAD

**Issue by graysky2** [grml/grml-etc-core#52]
A recent update on Arch Linux has caused the following warnings to appear directly after issuing a prompt command:
```
% prompt adam1 yellow 
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%(K{ <-- HERE .*?}|k)/ at -e line 1.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%(K{ <-- HERE .*?}|k)/ at -e line 1.
```

Arch runs version 0.12.1 of [grml-zsh-config](https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/grml-zsh-config).

I believe this warning coinsided with the perl 5.20.2 -> 5.22.0 update but I cannot be sure.

**Comment by ft** [comment]
Hi,

graysky wrote:
> A recent update on Arch Linux has caused the following warnings to
> appear directly after issuing a prompt command:
> ```
> % prompt adam1 yellow 
> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%(K{ <-- HERE .*?}|k)/ at -e line 1.
> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%(K{ <-- HERE .*?}|k)/ at -e line 1.
> ```

I'm not using arch, but I can't reproduce this with a fairly recent
git-build of zsh and grml-etc-core's master HEAD's zshrc.

Also, "Unescaped left brace" is NOT a message issued by zsh or our
setup. So, I don't know what you're doing over there. We'd need a lot
more detail, to start with.

Regards, Frank

**Comment by graysky2** [comment]
What version of perl are you running?

```
% perl --version

This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi
```

**Comment by graysky2** [comment]
Yes, it's definitely due to perl.  I spun up Arch in a LXC and when I switch to the adam1 yellow prompt under perl 5.20.2-1 I see no such warning.  As soon as I update to perl 5.22.0-1 and then invoke the same adam1 yellow theme via prompt, I get the warning.

**Comment by ft** [comment]
graysky wrote:
> Yes, it's definitely due to perl. I spun up Arch in a LXC and when I switch to
> the adam1 yellow prompt under perl 5.20.2-1 I see no such warning. As soon as I
> update to perl 5.22.0-1 and then invoke the same adam1 yellow theme via prompt,
> I get the warning.

That seems possible.

However, this is not a bug in grml-etc-core but upstream with zsh,
because that particular prompt theme calls out to perl.

There is nothing we can do about this; report this with zsh at
zsh-workers@zsh.org — you don't have to be subscribed, but can instead
ask to be CC:ed.

Regards, Frank

**Comment by graysky2** [comment]
Didn't know who was to blame :)  I will send out the zsh ML.  (I have been just redirecting to /dev/null but seems like it should be fixed).
