### ISSUE TITLE
The aliases in zshrc

### ISSUE THREAD

**Issue by LaoQi** [grml/grml-etc-core#63]
I use grml zsh config in my debian, It's so cool.
But when I install silver_searcher-ag.
The cmd `ag` alread alias `apt-get upgrade` in debian.

If you don't wanna change, ignore this issue.

The silver_searcher
 [https://github.com/ggreer/the_silver_searche](https://github.com/ggreer/the_silver_searcher) 
A code searching tool similar to ack, with a focus on speed.

**Comment by evgeni** [comment]
Just set `GRML_NO_APT_ALIASES=1`.

https://github.com/grml/grml-etc-core/blob/master/doc/grmlzshrc.t2t#L76

**Comment by LaoQi** [comment]
Ok

**Comment by nbraud** [comment]
@LaoQi Amusingly, that's _exactly_ the reason why I implemented `GRML_NO_APT_ALIASES` and `GRML_NO_SMALL_ALIASES` in #59  :)
