### ISSUE TITLE
zsh_history not being created

### ISSUE THREAD

**Issue by ejbolt** [grml/grml-etc-core#64]
Hello,
I added the grml-zsh-config as my .zshrc file.  However, as soon as I open a new terminal, all of my previous commands are gone.  None of my previous command line entries are saved, and that's a huge detriment as I use zsh-autosuggestions.  Is this an issue others have reported, or is there something extra I need to do?

**Comment by ft** [comment]
First time I hear of it.

After you start zsh with our setup as your `.zshrc` what does `echo $HISTFILE` say?
Also, `echo $HISTSIZE` and `echo $SAFEHIST`.

Which version of the setup are you using? `master` has c0a2a4d13a0d which touches the general area that breaks for you, though the diff looks simple enough... You can try and revert this change and see if the problem persists.

**Comment by ejbolt** [comment]
That did indeed fix it.  Thank you for such a quick response :). Seems to be the length of HISTSIZE that was the problem.  echo $HISTFILE said /home/*user*/.zsh_history, which was correct.
HISTSIZE is 30 and SAFEHIST was blank.

**Comment by ft** [comment]
Yeah, crap. Turns out, these have default values:

```
% zsh -fc 'echo $HISTSIZE $SAVEHIST'
30 0
```

I've lost track of zsh defaults somewhere in the last 20 year. :)

Anyway, this is pretty bad. Thanks for reporting.

I'll think about either reverting the patch or working around this. But working around this will make things much more inelegant. And I'm not thrilled about that.

**Comment by ejbolt** [comment]
Oddly enough, it only occurred on my Debian box where I used the method on the site to get the grml config, wget -O .zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc, whereas on my Arch Linux boxes where I installed from the user repo, it works fine.  

Sorry about that :/  Never fun when you gotta make your code/config/script messy.

**Comment by ft** [comment]
Really? Can you run that `zsh -fc ...` command from above on that system and tell me what that yields? I build zsh from source, because I'm kind of involved upstream too... So, I can tell you those are the defaults from an unmodified source tree (recent git build).

**Comment by ft** [comment]
The Arch system, I mean.

**Comment by ejbolt** [comment]
Currently trying to find it on the box.  It's odd how it is saved.

**Comment by ejbolt** [comment]
Interesting
`echo $HISTSIZE $SAVEHIST
1000 1000`
That's strange.  I had wondered if the AUR package was maybe not as up to date, but is that not the case?

**Comment by ft** [comment]
Do they have something weird in their global zshenv file? That file is sourced at startup, despite `-f`.

**Comment by ejbolt** [comment]
Where can I find that?

**Comment by ft** [comment]
"Depends" :)

You can try `strings =zsh | grep zshenv`, which should tell you.

**Comment by ejbolt** [comment]
Hmmm, when I run that it gives the output
`/etc/zsh/zshenv
.zshenv`
but when I go there, the file doesn't exist.  It's not hidden, just not there.

I apologize, my experience with zshenv files is lacking.

**Comment by ft** [comment]
It's `/etc/zsh/zshenv` then. That's what debian uses too. Make sure to run that command on the Arch system to find which file those guys use. (It's a compile time option)

**Comment by ejbolt** [comment]
Ah, it's the same in both    odd

**Comment by ft** [comment]
Okay. If the file exist, check if the parameters we're interested in are modified in that file.

**Comment by ejbolt** [comment]
That's the strange thing.  I get the same output in both systems, so on the Arch box, that command says it's there, but when I try to read it, text editor, cat, etc, it says I'm creating a new file.  Essentially, the file doesn't exist on the Arch box as far as I can tell.

**Comment by ft** [comment]
Try this: `zsh -f -o sourcetrace -c true`

If a file is sourced, the `sourcetrace` option will print that file's name.

**Comment by ejbolt** [comment]
Okay, that gives no output, so no file is sourced?

**Comment by ft** [comment]
Yes.

Other than that, I can only think of the parameters coming from your execution environment, where they might be set already.

If that's not the case, the Arch guys may indeed be patching the source. Can I take a look at their package build code? Do they have a patch tracker?

**Comment by ejbolt** [comment]
Hmmm, you can potentially pull it down from here? https://aur.archlinux.org/grml-zsh-config-git.git

I'll do some checking

**Comment by ejbolt** [comment]
OH!  Duh, it says it was last updated 2 years ago.  So it must be out of date

**Comment by ejbolt** [comment]
*facepalm*

**Comment by ft** [comment]
No, I mean their zsh package. Not the one of our setup.

I'd be surprised if they actually patched the sources for this, making their zsh incompatible from any other installation, but you never know.

I'd more guess for your execution environment having those parameters set.

**Comment by ft** [comment]
This seems to be it: https://aur.archlinux.org/cgit/aur.git/tree/?h=zsh-git
I don't see any patching in there. So I still think it's your execution environment on Arch.

No matter. The issue remains, and I'll deal with it in some way or another.

Thanks again for reporting this.

**Comment by ejbolt** [comment]
Not a problem!  Thanks for an awesome config :)

**Comment by ft** [comment]
This issue is fixed by af65087851
