### ISSUE TITLE
Inserting pipe+space inside parenthesis drops next words in command

### ISSUE THREAD

**Issue by sim590** [grml/grml-etc-core#65]
Let the following prompt:

```
$ $(foo) bar
       ^
```

where `^` indicates the cursor position. When inserting `|` followed by space, the resulting prompt is the following:

```
$ $(foo| )
         ^
```

This demonstrates that editing the command line might result in losing a significant part of the command.

**GRML revision**: af65087851ed8d2f74bd025b5862f5222884da97
**zsh version**: zsh 5.4.2 (x86_64-debian-linux-gnu)
**Distribution**: Debian GNU/Linux testing (buster)

**Comment by ft** [comment]
Thanks for the report.

I can reproduce this starting at `zsh -f` and binding `<SPACE>` to `magic-space.

I'm pretty sure this is a bug in zsh.  I wonder if this is a long-standing problem... ...anyway. I'll take care of it. Thanks again, for the report. I will close this report, as soon as I verified that this is indeed an upstream issue.

**Comment by ft** [comment]
Reported upstream with zsh itself (Cc:ed you in my mail to the mailing list). This is not an issue with our setup, but a bug in zsh. Closing therefore.
