### ISSUE TITLE
Multiline command re-echoing when using urxvt

### ISSUE THREAD

**Issue by cddmp** [grml/grml-etc-core#74]
When running multiline commands in urxvt, parts of the command are re-echoed. 

Example:
````
me@system ~/foo % ls \
\`> -l

-ltotal 0
-rw-r--r-- 1 me users 0 Feb 27 20:36 bar1
-rw-r--r-- 1 me users 0 Feb 27 20:36 bar2
me@system ~/foo %
````
Note the '-l' be re-echoed in front of 'total'.

After some debugging it turned out that the problems is in the function info_print() which is called by set_title(). urxvt seems to wrongly handle the newline character. A fix would be to replace line 2484 in zshrc which is 

`printf '%s' "$*"`

with

`printf '%s' "${*//[$'\n']}"`

Since this problem seems to be limited to urxvt, this might be something which need to be actually fixed in urxvt. I just wanted to bring it up here. Others seem to have come across the same issue:
https://stackoverflow.com/questions/16120888/grmls-zsh-config-multiline-command-re-echoing

**Comment by mika** [comment]
Thanks for reporting this, @cddmp! @ft are you aware of anything that we could do about it?

**Comment by ft** [comment]
Will try to look at it this weekend. Can't promise, though.

**Comment by cantandwont** [comment]
I used zsrc.local to redefine the function `grml_control_xterm_title` from [zshrc](https://github.com/grml/grml-etc-core/blob/ffe57c8786bf71c015d948eff4253089725b9f8e/etc/zsh/zshrc#L2525), changing
`set_title "${(%):-"%n@%m:"}" "$1"`
to
`set_title "${(%):-"%n@%m:"}" "${(z)1}"`

**Comment by cantandwont** [comment]
Tried out Alacritty - it trims from the window title anything after (and incl.) the first newline or semicolon, whether it's quoted or not (eg. when running `echo "12;3" | ...` window title has `echo "12`).
Alacritty had no problem with re-echoing lines after the prompt.
For now, I'm going with urxvt and `set title` ... `"${1%%[[:cntrl:]]*}"` in zshrc

**Comment by cddmp** [comment]
@cantandwont: Your solution trims everything after the newline character, the solution I presented above does not.

**Comment by cantandwont** [comment]
@cddmp Absolutely. For me long running commands needn't display any more than the first line in the window title (but that's just me). Simply removing all newlines does cause the window title to be slightly incorrect - everything is just runtogetherlikethis - using `z` &/or `f` flag here makes sense to me. Have you tried that? I liked how the z flag formats things.

Also, I had wondered if doing this "cleanup" (removing newlines in whichever fashion) would be better done in `grml_control_xterm_title ()` - ie. earlier rather later, other functions use `info_print ()` - `grml_cmd_to_screen_title` & `grml_vcs_to_screen_title` and they might not need "cleaning up"(?).

**Comment by cddmp** [comment]
@cantandwont: Thanks for your reply! Originally I didn't want to create a pull request, because I wonder if this is something which is better fixed in the terminal itself (see my original post). I just thought trimming everything after newline is not a good solution (and more "incorrect" than trimming newlines ;)).
I will try the flags you mentioned. :)

> Also, I had wondered if doing this "cleanup" (removing newlines in whichever fashion) would be better done in `grml_control_xterm_title ()` - ie. earlier rather later, other functions use `info_print ()` - `grml_cmd_to_screen_title` & `grml_vcs_to_screen_title` and they might not need "cleaning up"(?).
Yep I wondered about this as well. I haven't tried screen so far. Did you?

**Comment by cantandwont** [comment]
@cddmp I haven't tried screen.

I'm sorry if creating a PR for this was inappropriate. After trying out the `${(f)${(z)1}}` change, I've updated my PR #80 to this - any comments are welcome! :)

**Comment by cantandwont** [comment]
ok ok ok, I'm feeling pretty silly now - scrap all of my prior suggestions - and just replace $1 with $2 (in grml_control_xterm_title). Please let me know what you think :)

**Comment by cddmp** [comment]
Sorry for being late. @cantandwont your last fix is great and a perfect solution. Thanks for digging deeper into this!
