### ISSUE TITLE
zshrc: mount ./arch<tab> autocompletion issue

### ISSUE THREAD

**Issue by cynecx** [grml/grml-etc-core#75]
I am having an issue with the zshrc config. It seems that the autocompletion for `mount` is broken?

Steps to reproduce:

```bash
mkdir test && cd test
touch archlinux-2018.07.01-i686.iso
touch archlinux-2019.03.01-x86_64.iso
mount ./arch<tab> # completes to: mount ./archlinux-201.0.01-<|>.iso, where <|> is the cursor
```

https://asciinema.org/a/A28U4Snpkv4qFDEsXIlRzmnuT

**Comment by mika** [comment]
Thanks for reporting this and providing the necessary steps to reproduce this issue.

@ft, any chance you could take a look at this?

**Comment by cynecx** [comment]
ping.

**Comment by mika** [comment]
It's not specific to grml-zshrc, I've forwarded this towards Zsh upstream: http://www.zsh.org/mla/workers/2019/msg00400.html

**Comment by cynecx** [comment]
@mika Thanks :). I guess we can close this issue then!
