### ISSUE TITLE
Zsh config ignore locale.

### ISSUE THREAD

**Issue by Suyun-blog** [grml/grml-etc-core#83]
OS: Debian sid
Zsh version: 5.7.1

First, the `LANG` variable was set as `"zh_CN.UTF-8"`.

On Bash and Zsh without the config, all the locale variables (such as `LC_CTYPE` and `LC_TIME`) can be set as `"zh_CN.UTF-8"`.

 but when I add the Zsh config, only the `LANG` variable was set, and others are `"C"`.

Confusingly, the problem can not happen on Ubuntu.

**Comment by mika** [comment]
Hi @Suyun-blog, we need more information regarding your setup. 

1. Which version of grml-zshrc are you using? The latest one from git?
2. What's inside your `/etc/default/locale`?
3. What's the output of `echo "LANG = $LANG | LC_CTYPE = $LC_CTYPE | LC_TIME = $LC_TIME | LC_ALL = $LC_ALL"` on your system?
4. Which zsh configurations do you have on your system (`/etc/zsh/...`, `~/.zshrc*`) and which one do you mean when refering to "when I add the Zsh config"?

**Comment by Suyun-blog** [comment]
Thank you for replying me.

I found the reason. I use `dpkg-reconfigure locales` to set the locale in Debian, and the tool not only set `LANG` but also set `LANGUAGE` as `en_US.UTF-8`, and `LC_ALL` as `C`.

And in Ubuntu, I use `update-locale` directly. It works well.
