### ISSUE TITLE
`edit-command-line` binding problems in vi-mode

### ISSUE THREAD

**Issue by hexhexd** [grml/grml-etc-core#90]
I'm using grml-zsh-config from Arch repo grml-zsh-config 0.16.1-1.

ESC-e: Edit the current line in$EDITOR works in emacs mode but not in vi mode.

**Comment by ft** [comment]
Moved the issue to grml-etc-core, which contains our zsh configuration.

**Comment by hexhexd** [comment]
Setting KEYTIMEOUT=20 solved my problem, I guess I just have slow fingers lol.

Again, thank you very much for taking your time to answer my questions, and grml-zsh-config has made my terminal a joy to use.

**Comment by mika** [comment]
So I assume we can close the issue now? Thanks for assistence, @ft and thanks for reporting back, @hexhexd!
