### ISSUE TITLE
zshrc: warning, when hostname is not found

### ISSUE THREAD

**Issue by apt-ghetto** [grml/grml-etc-core#96]
I am using Arch Linux with systemd and have downloaded the .zshrc config from here.

It was shown a warning, that "hostname" was not found, which is true, because it is not installed. And because i did not want to install another package, I have "fixed" this on my machine by replacing
```
$(hostname)
```
with
```
$(hostnamectl --static)
```

I would appreciate, if you could add a check for `hostname` and `hostnamectl`.

**Comment by mika** [comment]
@apt-ghetto does https://github.com/grml/grml-etc-core/pull/97 fix the issue for you?
@ft @jkirk  I'd appreciate if you could briefly check whether https://github.com/grml/grml-etc-core/pull/97 makes sense for you,  thanks :)

**Comment by apt-ghetto** [comment]
@mika Yes, it is working for me. Thank you.

**Comment by jkirk** [comment]
This might be a silly question, but is it possible to have non of both?

**Comment by mika** [comment]
> This might be a silly question, but is it possible to have non of both?

Could be, though have never seen that myself and before introducing a workaround (like falling back to `/etc/hostname`) I would like to know about it :)

**Comment by moviuro** [comment]
`uname -n` looks like the way to go. It's [actually POSIX](https://pubs.opengroup.org/onlinepubs/009695399/utilities/uname.html)
